#!MC 1410
$!VarSet |MFBD| = 'C:\Users\Ilya\Dropbox\Science\!Projects\ReplicatorNKT'
$!READDATASET  '"|MFBD|\out.dat" '
  READDATAOPTION = NEW
  RESETSTYLE = YES
  VARLOADMODE = BYNAME
  ASSIGNSTRANDIDS = YES
$!PLOTTYPE = CARTESIAN2D
$!FIELDLAYERS SHOWSHADE = NO
$!TRIANGULATE
$!RemoveVar |MFBD|
